### ISSUE TITLE
undefined method `push' for #<Hash:0x007fed931530a0>

### ISSUE THREAD

**Issue by exocode** [assembler/attachinary#27]
After some trial and error I must confirm that "EDITING and UPDATING" a model cause this issue:

 ## NoMethodError in LocationsController#update ##

```
undefined method `push' for #<Hash:0x007fed931530a0>
```

app/controllers/locations_controller.rb:79:in `block in update'
app/controllers/locations_controller.rb:78:in`update

The depending line is:

```
78:     respond_to do |format| 
79:       if @location.update_attributes(params[:location])
```

when I comment_out this line in the form             

```
<%= attachinary_file_field_tag 'location[image]', @location, :image %>
```

and save/update the edited model all works fine.

I am working with the mongoid ORM (mongoid 2.4)

any suggestions?

_Parameters_

"image"=>"[{\"format\":\"jpg\",
\"public_id\":\"qw8toyokwzstksukinu8\",
\"resource_type\":\"image\",
\"version\":\"1351470251\",
\"path\":\"v1351470251/qw8toyokwzstksukinu8.jpg\"}]",
 "logo"=>"[{\"format\":\"jpg\",
\"public_id\":\"dsmsnc7a5qjnvprwmwkc\",
\"resource_type\":\"image\",
\"version\":\"1351470255\",
\"path\":\"v1351470255/dsmsnc7a5qjnvprwmwkc.jpg\"}]"},
 "commit"=>"Submit Location!",
 "id"=>"508dc953b7807e1aa7000026"}
# Stack Trace

mongoid (2.4.12) lib/mongoid/atomic/modifiers.rb:122:in `block in add_operation'
mongoid (2.4.12) lib/mongoid/atomic/modifiers.rb:121:in`each'
mongoid (2.4.12) lib/mongoid/atomic/modifiers.rb:121:in `add_operation'
mongoid (2.4.12) lib/mongoid/atomic/modifiers.rb:87:in`block in set'
mongoid (2.4.12) lib/mongoid/atomic/modifiers.rb:84:in `each_pair'
mongoid (2.4.12) lib/mongoid/atomic/modifiers.rb:84:in`set'
mongoid (2.4.12) lib/mongoid/atomic.rb:277:in `generate_atomic_updates'
mongoid (2.4.12) lib/mongoid/atomic.rb:105:in`block (2 levels) in atomic_updates'
mongoid (2.4.12) lib/mongoid/atomic.rb:104:in `each'
mongoid (2.4.12) lib/mongoid/atomic.rb:104:in`block in atomic_updates'
mongoid (2.4.12) lib/mongoid/atomic.rb:102:in `tap'
mongoid (2.4.12) lib/mongoid/atomic.rb:102:in`atomic_updates'
mongoid (2.4.12) lib/mongoid/persistence/operations.rb:157:in `init_updates'
mongoid (2.4.12) lib/mongoid/persistence/operations.rb:130:in`updates'
mongoid (2.4.12) lib/mongoid/persistence/operations/update.rb:44:in `block in persist'
mongoid (2.4.12) lib/mongoid/persistence/modification.rb:25:in`block (2 levels) in prepare'
activesupport (3.2.3) lib/active_support/callbacks.rb:403:in `_run__2553662088574445908__update__1039413575395477817__callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_update_callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:81:in`run_callbacks'
mongoid (2.4.12) lib/mongoid/callbacks.rb:43:in `run_callbacks'
mongoid (2.4.12) lib/mongoid/persistence/modification.rb:24:in`block in prepare'
activesupport (3.2.3) lib/active_support/callbacks.rb:414:in `_run__2553662088574445908__save__1039413575395477817__callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:81:in`run_callbacks'
mongoid (2.4.12) lib/mongoid/callbacks.rb:43:in `run_callbacks'
mongoid (2.4.12) lib/mongoid/persistence/modification.rb:23:in`prepare'
mongoid (2.4.12) lib/mongoid/persistence/operations/update.rb:43:in `persist'
mongoid (2.4.12) lib/mongoid/persistence.rb:91:in`update'
mongoid (2.4.12) lib/mongoid/persistence.rb:156:in `upsert'
mongoid (2.4.12) lib/mongoid/persistence.rb:120:in`update_attributes'
actionpack (3.2.3) lib/action_controller/metal/mime_responds.rb:270:in `call'
actionpack (3.2.3) lib/action_controller/metal/mime_responds.rb:270:in`retrieve_collector_from_mimes'
actionpack (3.2.3) lib/action_controller/metal/mime_responds.rb:194:in `respond_to'
actionpack (3.2.3) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.2.3) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.3) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.2.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.3) lib/active_support/callbacks.rb:425:in`_run__2911065496874474384__process_action__533950475842813760__callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.3) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.3) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.3) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.2.3) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.3) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (3.2.3) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.3) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.2.3) lib/action_controller/metal/params_wrapper.rb:205:in `process_action'
actionpack (3.2.3) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.2.3) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.3) lib/action_controller/metal.rb:203:in`dispatch'
actionpack (3.2.3) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.3) lib/action_controller/metal.rb:246:in`block in action'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in`block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in`call'
......
.....
....
...
..
.
